@host = http://localhost:3500



### whoami
GET {{host}}/auth/whoami

### logout
POST {{host}}/auth/signout


### get user
GET {{host}}/auth/11
### get user
GET {{host}}/auth/222


### get users
### get user by email
GET {{host}}/auth?email=ans@gmail.com
### get user by email error
GET {{host}}/auth?email=123

### signup
POST {{host}}/auth/signup
Content-Type: application/json

{
  "email": "ans2@gmail.com",
  "pwd": "readddl"
}
### signup error
POST {{host}}/auth/signup
Content-Type: application/json

{
  "email": "ansgmailcom"
}

### signin
POST {{host}}/auth/signin
Content-Type: application/json

{
  "email": "ans1@gmail.com",
  "pwd": "readddl"
}

### update
PATCH {{host}}/auth/2
Content-Type: application/json

{
  "pwd": "readdd22222111122"
}

### remove
DELETE  {{host}}/auth/10


### Set a color
GET {{host}}/auth/colors/red111

### get a color 
GET {{host}}/auth/colors
